In [10]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Review

## Discussion Question 1

The past weeks temperatures in Fahrenheit were:
70, 68, 66, 71, 72, 70, 68

The connection between Fahrenheit temperature F and Celsius temperature C is:
C = 5/9(F - 32)

Use an array calculation to convert all these Fahrenheit temperatures to Celsius.

In [9]:
fahrenheit_temps = make_array(70, 68, 66, 71, 72, 70, 68)
celsius_temps = 5 / 9 * (fahrenheit_temps - 32)
celsius_temps

array([ 21.11111111,  20.        ,  18.88888889,  21.66666667,
        22.22222222,  21.11111111,  20.        ])

In [4]:
# Bonus: Round them all to one decimal place
celsius_temps = np.round(celsius_temps, 1)
celsius_temps

array([ 21.1,  20. ,  18.9,  21.7,  22.2,  21.1,  20. ])

## Discussion Question 2

A lemonade stand sold
- 50 cups of lemonade at $3.50 each
- 35 bottles of water at $2.00 each
- 25 cookies at $3.00 each

Create an array for sales and an array for cost. Use these to produce a third array for revenue generated by each item (lemonade revenue in the first entry, water revenue in the second, and cookie revenue in the third).

In [5]:
sales = make_array(50, 35, 25)
cost = make_array(3.50, 2.00, 3.00)
revenue = sales * cost
revenue

array([ 175.,   70.,   75.])

In [6]:
# Bonus: The total revenue is
np.sum(revenue)

320.0

# Ranges

In [11]:
# One argument gives an array from 0 to the integer provided (excluding right endpoint)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Two arguments denotes the starting value (inclusive) and ending value (exclusive)
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [13]:
# Three arguments denotes the starting value, ending value, and step size
np.arange(5, 10, 2)


array([5, 7, 9])

# Functions on Arrays (textbook 5.1)

In [14]:
nums = np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [15]:
np.sum(nums)

10

In [18]:
np.diff(nums)

array([1, 1, 1, 1])

In [19]:
np.mean(nums)

2.0

# Practice

1. Use arange to generate the following approximation of $\pi$:

$$4 \cdot \left( \left(1 + \frac{1}{5} + \frac{1}{9} + \dots + \frac{1}{9997} \right) - \left(\frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \dots + \frac{1}{9999} \right) \right)$$

- Use arange to generate an array containing 1, 5, 9, ... , 9997
- Use / to generate an array containing 1/1, 1/5, 1/9, ..., 1/9997
- Sum the elements of this array to get the value of the first parenthesis
- Go through a similar process to get the second parenthesis
- Calculuate the estimate

In [40]:
denoms1 = np.arange(1,9998,4)
fracs1 = 1 / denoms1
positive_sum = np.sum(fracs1)
positive_sum

3.0128498864750557

In [39]:
denoms2 = np.arange(3,10000,4)
fracs2 = 1 / denoms2
negative_sum = np.sum(fracs2)
negative_sum

2.2275017230771077

In [38]:
4 * (positive_sum - negative_sum)

3.1413726315867336

2. Use arange to generate the following approximation of $\pi$:
$$2 \cdot \left( \frac{2}{1} \cdot \frac{4}{3} \cdot \frac{6}{5} \cdots \frac{1,000,000}{999999} \right) \cdot \left( \frac{2}{3} \cdot \frac{4}{5} \cdot \frac{6}{7} \cdots \frac{1,000,000}{1,000,001} \right)$$

In [47]:
numerators = np.arange(2,1000001,2)
denoms1 = np.arange(1, 1000000,2)
denoms2 = np.arange(3,1000002,2)

In [50]:
fracs1 = numerators / denoms1
fracs2 = numerators / denoms2

In [51]:
prod1 = np.prod(fracs1)
prod2 = np.prod(fracs2)

In [52]:
2 * prod1 * prod2

3.1415910827951143