In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Columns of Tables are Arrays ##

In [19]:
nba = Table.read_table('nba_salaries.csv').relabeled(4, 'SALARY')
warriors = nba.where('team', 'Golden State Warriors')

In [3]:
warriors

rank | name              | position | team                  | SALARY  | season
41   | Donyell Marshall  | PF       | Golden State Warriors | 5250000 | 2000
47   | Erick Dampier     | C        | Golden State Warriors | 4988000 | 2000
58   | Mookie Blaylock   | G        | Golden State Warriors | 4200000 | 2000
59   | Chris Mills       | SF       | Golden State Warriors | 4200000 | 2000
64   | Jason Caffey      | F        | Golden State Warriors | 3937000 | 2000
89   | Vonteego Cummings | PG       | Golden State Warriors | 2600000 | 2000
92   | Antawn Jamison    | PF       | Golden State Warriors | 2503000 | 2000
73   | Erick Dampier     | C        | Golden State Warriors | 5611000 | 2001
91   | Mookie Blaylock   | G        | Golden State Warriors | 4800000 | 2001
92   | Chris Mills       | SF       | Golden State Warriors | 4800000 | 2001
... (301 rows omitted)

In [24]:
salary_select = warriors.select('SALARY')
salary_select

SALARY
5250000
4988000
4200000
4200000
3937000
2600000
2503000
5611000
4800000
4800000
... (301 rows omitted)

In [25]:
type(salary_select)
# Returns a column in a table format

datascience.tables.Table

In [29]:
salary_col = warriors.column('SALARY')
salary_col


array([ 5250000,  4988000,  4200000,  4200000,  3937000,  2600000,
        2503000,  5611000,  4800000,  4800000,  4386000,  3578000,
        3390000,  2678000,  1842000,   757000,   316000,   316000,
         241000,    32000,  6235000,  5400000,  5400000,  4913000,
        4441000,  4400000,  3388000,  3000000,  2343000,  2021000,
        1310000,   333000,   333000,  6858000,  6000000,  5540000,
        4935000,  4469000,  4400000,  1409000,   700000,   512000,
       10912000,  7482000,  5445000,  4400000,  1667000,  1507000,
        3000000,  2481000,  2390000,  2232000, 13700000,  8888888,
        7365079,  7312500,  5393300,  4506261,  1988160,  1910520,
        1857360,  1760000,  1404360,   448762,   423762, 15070000,
        9999999,  8125000,  2535260,  2157097,  2061720,  1986960,
         798112,   744551,   664209,   259770, 16440000,  8425625,
        6630000,  4000000,  3470771,  3000000,  2636696,  2323080,
        2216400,  1800000,  1345800,   770610,   770610,   687

In [30]:
type(salary_col)

numpy.ndarray

In [32]:
# np.average(salary_select)
# can't call numpy function on tables

In [33]:
np.average(salary_col)

4315935.9228295824

In [36]:
mills_salary_table = warriors.where('name', 'Chris Mills')
mills_salary_array = mills_salary_table.column('SALARY')
mills_salary_array

array([4200000, 4800000, 5400000, 6000000])

In [37]:
np.average(mills_salary_array)

5100000.0

In [40]:
warriors.where('name', 'Chris Mills').column('SALARY').item(0)

4200000

## Census ##

In [41]:
full = Table.read_table('nc-est2019-agesex-res.csv')
full

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | POPESTIMATE2016 | POPESTIMATE2017 | POPESTIMATE2018 | POPESTIMATE2019
0    | 0    | 3944153       | 3944160           | 3951430         | 3963092         | 3926570         | 3931258         | 3954787         | 3983981         | 3954773         | 3893990         | 3815343         | 3783052
0    | 1    | 3978070       | 3978090           | 3957730         | 3966225         | 3977549         | 3942698         | 3948891         | 3973133         | 4002903         | 3972711         | 3908830         | 3829599
0    | 2    | 4096929       | 4096939           | 4090621         | 3970654         | 3978925         | 3991740         | 3958711         | 3966321         | 3991349         | 4020045         | 3987032         | 3922044
0    | 3    | 4119040       | 4119051           | 4111688         | 4101644         | 3981531         | 3991017         | 4005928         | 3974351         | 3982984         | 4006946         | 4033038         | 3998665
0    | 4    | 4063170       | 4063186           | 4077346         | 4121488         | 4111490         | 3992502         | 4004032         | 4020292         | 3989750         | 3997280         | 4018719         | 4043323
0    | 5    | 4056858       | 4056872           | 4064521         | 4087054         | 4131049         | 4121876         | 4004576         | 4017589         | 4035033         | 4003452         | 4008443         | 4028281
0    | 6    | 4066381       | 4066412           | 4072904         | 4074531         | 4096631         | 4141126         | 4133372         | 4017388         | 4031568         | 4048018         | 4014057         | 4017227
0    | 7    | 4030579       | 4030594           | 4042990         | 4082821         | 4084175         | 4106756         | 4152666         | 4145872         | 4030888         | 4044139         | 4058370         | 4022319
0    | 8    | 4046486       | 4046497           | 4025501         | 4052773         | 4092559         | 4094513         | 4118349         | 4165033         | 4158848         | 4042924         | 4054236         | 4066194
0    | 9    | 4148353       | 4148369           | 4125312         | 4035319         | 4062726         | 4103052         | 4106068         | 4130887         | 4177895         | 4170813         | 4053179         | 4061874
... (296 rows omitted)

In [42]:
one_year_growth = full.select('SEX', 'AGE', 'CENSUS2010POP', 'POPESTIMATE2011')
one_year_growth

SEX  | AGE  | CENSUS2010POP | POPESTIMATE2011
0    | 0    | 3944153       | 3963092
0    | 1    | 3978070       | 3966225
0    | 2    | 4096929       | 3970654
0    | 3    | 4119040       | 4101644
0    | 4    | 4063170       | 4121488
0    | 5    | 4056858       | 4087054
0    | 6    | 4066381       | 4074531
0    | 7    | 4030579       | 4082821
0    | 8    | 4046486       | 4052773
0    | 9    | 4148353       | 4035319
... (296 rows omitted)

In [43]:
one_year_growth = one_year_growth.where('SEX', 0)
one_year_growth

SEX  | AGE  | CENSUS2010POP | POPESTIMATE2011
0    | 0    | 3944153       | 3963092
0    | 1    | 3978070       | 3966225
0    | 2    | 4096929       | 3970654
0    | 3    | 4119040       | 4101644
0    | 4    | 4063170       | 4121488
0    | 5    | 4056858       | 4087054
0    | 6    | 4066381       | 4074531
0    | 7    | 4030579       | 4082821
0    | 8    | 4046486       | 4052773
0    | 9    | 4148353       | 4035319
... (92 rows omitted)

In [14]:
one_year_growth = one_year_growth.drop('SEX')
one_year_growth

AGE  | CENSUS2010POP | POPESTIMATE2011
0    | 3944153       | 3963092
1    | 3978070       | 3966225
2    | 4096929       | 3970654
3    | 4119040       | 4101644
4    | 4063170       | 4121488
5    | 4056858       | 4087054
6    | 4066381       | 4074531
7    | 4030579       | 4082821
8    | 4046486       | 4052773
9    | 4148353       | 4035319
... (92 rows omitted)

In [15]:
pop2010 = one_year_growth.column('CENSUS2010POP')
pop2010


array([  3944153,   3978070,   4096929,   4119040,   4063170,   4056858,
         4066381,   4030579,   4046486,   4148353,   4172541,   4114415,
         4106243,   4118013,   4165982,   4242820,   4316139,   4395295,
         4500855,   4585234,   4519129,   4354294,   4264642,   4198571,
         4249363,   4262350,   4152305,   4248869,   4215249,   4223076,
         4285668,   3970218,   3986847,   3880150,   3839216,   3956434,
         3802087,   3934445,   4121880,   4364796,   4383274,   4114985,
         4076104,   4105105,   4211496,   4508868,   4519761,   4535265,
         4538796,   4605901,   4660295,   4464631,   4500846,   4380354,
         4291999,   4254709,   4037513,   3936386,   3794928,   3641269,
         3621131,   3492596,   3563182,   3483884,   2657131,   2680761,
         2639141,   2649365,   2323672,   2142324,   2043121,   1949323,
         1864275,   1736960,   1684487,   1620077,   1471070,   1455330,
         1400123,   1371195,   1308511,   1212865, 

In [16]:
est2011 = one_year_growth.column('POPESTIMATE2011')
est2011

array([  3963092,   3966225,   3970654,   4101644,   4121488,   4087054,
         4074531,   4082821,   4052773,   4035319,   4135275,   4197127,
         4125724,   4123811,   4130861,   4158280,   4246693,   4334152,
         4401220,   4518136,   4598087,   4594046,   4412989,   4312071,
         4242005,   4267715,   4311460,   4181235,   4255887,   4264231,
         4224904,   4316834,   4053130,   3977087,   3941571,   3829296,
         3953574,   3834160,   3899275,   4081727,   4323492,   4384667,
         4160003,   4078457,   4088648,   4171392,   4429559,   4518765,
         4522525,   4519850,   4582117,   4627614,   4478988,   4458856,
         4416050,   4263777,   4233221,   4066454,   3918867,   3773861,
         3664938,   3586380,   3487750,   3459686,   3612778,   2674388,
         2644949,   2585082,   2652967,   2320909,   2128978,   2022302,
         1911768,   1839617,   1705176,   1638392,   1581264,   1430846,
         1394624,   1343872,   1292555,   1252415, 

In [17]:
percent_growth = ((est2011 / pop2010) - 1) * 100
percent_growth

array([  0.48017914,  -0.29775746,  -3.08218668,  -0.42233142,
         1.43528329,   0.74431987,   0.20042392,   1.29614132,
         0.15536937,  -2.72479222,  -0.89312484,   2.01029794,
         0.47442394,   0.14079606,  -0.84304253,  -1.9925427 ,
        -1.60898433,  -1.39110117,  -2.21369051,  -1.46334953,
         1.74719509,   5.50610501,   3.47853349,   2.70330072,
        -0.17315536,   0.12586953,   3.83293135,  -1.59181184,
         0.96407116,   0.97452662,  -1.41784198,   8.73040221,
         1.66254185,   2.49827971,   2.66603911,  -3.21344928,
         3.98431177,  -2.54889826,  -5.40056964,  -6.48527445,
        -1.36386637,   6.55365694,   2.05831353,  -0.64914296,
        -2.91696822,  -7.48471678,  -1.995725  ,  -0.36381557,
        -0.35848714,  -1.86827724,  -1.67753329,   3.65053685,
        -0.48564203,   1.79213826,   2.89028492,   0.21312856,
         4.84724136,   3.30424913,   3.26591176,   3.64136789,
         1.20976016,   2.68522326,  -2.1169842 ,  -0.69

In [18]:
one_year_growth = one_year_growth.with_column('%_POINTS_GROWTH', percent_growth)
one_year_growth

AGE  | CENSUS2010POP | POPESTIMATE2011 | %_POINTS_GROWTH
0    | 3944153       | 3963092         | 0.480179
1    | 3978070       | 3966225         | -0.297757
2    | 4096929       | 3970654         | -3.08219
3    | 4119040       | 4101644         | -0.422331
4    | 4063170       | 4121488         | 1.43528
5    | 4056858       | 4087054         | 0.74432
6    | 4066381       | 4074531         | 0.200424
7    | 4030579       | 4082821         | 1.29614
8    | 4046486       | 4052773         | 0.155369
9    | 4148353       | 4035319         | -2.72479
... (92 rows omitted)